name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Anime action
      id: set-env
      run: echo "CUSTOM_URL=https://myanimeaction.com" >> $GITHUB_ENV  # Replace with your custom URL
    - name: Output Custom URL
      run: echo "Custom URL is: $CUSTOM_URL"
    - name: Display Deployment Information
      run: echo "Deployment completed. Access your site at: $CUSTOM_URL"
